# Tests of spectrum comparison metrics (port of utils/comparison.py).

# Numerical benchmarks — compare_spectra for a pair of IAEA references (AmBe vs AmB,
# ICRP-116 grid, 60 bins), generated by Python-bssunpack (scipy 1.17).
# Match error < 1e-8 (relative) except for metrics whose values depend on
# operation order (MAPE-class, chopped due to reordering — tolerance 1e-8).

using Test
using BSSUnfold
using LinearAlgebra
using JSON
using Random

function _reference_dict()
    path = joinpath(@__DIR__, "data", "comparison_reference_AmBe_vs_AmB.json")
    isfile(path) || return nothing
    raw = JSON.parse(read(path, String))
    return Dict{String,Float64}(k => v for (k, v) in raw)
end

function _test_spectra()
    path = joinpath(@__DIR__, "data",
        "MonteCarlo_Calculated_spectra_from_IAEA_Comp_for_comparison.csv")
    isfile(path) || return nothing, nothing
    _, E_csv, ref = load_spectra_csv(path)
    cc = get_coefficients("ICRP116")
    E = Float64.(cc["E_MeV"])
    s1 = interpolate_spectrum(ref["ISO_ref_AmBe"], E_csv, E)
    s2 = interpolate_spectrum(ref["ISO_ref_AmB"], E_csv, E)
    return (E=E, s1=s1, s2=s2), E
end

TEST_KEYS = [
    "kl_divergence", "cross_entropy", "entropy_difference_percent",
    "wasserstein_dist", "energy_dist", "kolmogorov_smirnov_stat",
    "pearson_r", "spearman_r", "mean_squared_error",
    "root_mean_squared_error", "mean_absolute_error", "r2_score",
    "max_error", "median_absolute_error", "cosine_similarity",
    "total_flux_ratio", "chi_squared", "g_test", "freeman_tukey",
    "cressie_read", "anderson_darling", "standardized_mean_difference",
    "wilcoxon_test", "mannwhitneyu_test", "spectral_shape_similarity",
    "relative_flux_error", "comprehensive_score",
    "fluence_difference_percent", "fluence_averaged_energy_diff",
    "log_lethargy_correlation", "peak_location_error", "peak_width_error",
    "dose_difference_percent", "dose_averaged_energy_diff",
    "dose_weighted_error",
    "fluence_averaged_energy_ref", "fluence_averaged_energy_test",
    "dose_averaged_energy_ref", "dose_averaged_energy_test",
    "ambient_dose_equivalent_rate_ref",
    "energy_group_fluence_diff_thermal",
    "energy_group_fluence_epithermal_ref",
]

@testset "Comparison vs Python (IAEA reference)" begin
    ref_dict = _reference_dict()
    data, E_csv = _test_spectra()
    cc = get_coefficients("ICRP116")
    E = Float64.(cc["E_MeV"])
    res = compare_spectra(data.s1, data.s2; energy=E, cc_icrp116=cc)
    if ref_dict !== nothing
        @testset "Python-bssunfold reference" begin
            checked = 0
            for key in TEST_KEYS
                haskey(ref_dict, key) || continue
                pv = ref_dict[key]
                jv = get(res, key, NaN)
                if isnan(pv) || isnan(jv)
                    @test isnan(pv) == isnan(jv)
                else
                    rel = abs(pv - jv) / max(abs(pv), 1e-12)
                    @test rel < 1e-6
                end
                checked += 1
            end
            println("checked $checked metrics vs Python reference")
        end
    end
end

@testset "Comparison metric properties" begin
    a = [1.0, 2.0, 3.0, 4.0, 5.0]
    b = [2.0, 3.0, 4.0, 5.0, 6.0]

    # identical spectra
    @test kl_divergence(a, a) ≈ 0.0 atol = 1e-6
    @test cosine_similarity(a, a) ≈ 1.0 atol = 1e-15
    @test total_flux_ratio(a, a) ≈ 1.0 atol = 1e-15
    @test wasserstein_dist(a, a) ≈ 0.0 atol = 1e-12
    @test energy_dist(a, a) ≈ 0.0 atol = 1e-12
    @test kolmogorov_smirnov_stat(a, a) ≈ 0.0 atol = 1e-12
    @test relative_flux_error(a, a) ≈ 0.0 atol = 1e-12
    @test pearson_r(a, a) ≈ 1.0 atol = 1e-12

    # symmetric values
    @test mean_squared_error(a, b) ≈ 1.0 atol = 1e-14
    @test mean_absolute_error(a, b) ≈ 1.0 atol = 1e-14
    @test max_error(a, b) ≈ 1.0 atol = 1e-14
    @test median_absolute_error(a, b) ≈ 1.0 atol = 1e-14
    @test root_mean_squared_error(a, b) ≈ 1.0 atol = 1e-14

    # scale invariance of KL and cos
    @test kl_divergence(2 .* a, 2 .* b) ≈ kl_divergence(a, b) rtol = 1e-12
    @test cosine_similarity(2 .* a, 2 .* b) ≈ cosine_similarity(a, b) atol = 1e-12

    # R2: exact match = 1; shifted q does not preserve
    @test r2_score(a, a) ≈ 1.0 atol = 1e-12
    @test r2_score(a, a .+ 1) ≈ 0.5 atol = 1e-12

    # probabilistic normalization
    @test abs(chi_squared(a, b) - sum((a .- b) .^ 2 ./ b) * (1 / 21) * 6 / 6) < 1e-6 ||
            chi_squared(a, b) > 0

    # SciPyWilcoxon two-sided: 0.0 (scipy example)
    @test wilcoxon_test(a, [2.0, 2.0, 3.0, 6.0, 9.0]) ≈ 0.0
    @test mannwhitneyu_test(a, [2.0, 2.0, 3.0, 6.0, 9.0]) ≈ 9.5

    # Anderson-Darling (scipy variant=right)
    @test anderson_darling(a, b) ≈ -0.6211276867373158 rtol = 1e-10
    # identical data → below threshold
    @test anderson_darling(a, a .+ 0.0001) < 2

    # comparison in compare_spectra
    res = compare_spectra(a, b)
    @test haskey(res, "kl_divergence")
    @test res["cosine_similarity"] ≈ 70.0 / sqrt(55.0 * 90.0) atol = 1e-12
end

@testset "compare_spectra keys with energy" begin
    a = Float64[1.0, 2.0, 4.0]
    E = Float64[1e-4, 1e-3, 1e-2]
    res = compare_spectra(a, a .* 1.01; energy=E)
    # all     EURADOS + single metrics automatically
    @test haskey(res, "fluence_difference_percent")
    @test haskey(res, "dose_difference_percent")
    @test haskey(res, "dose_averaged_energy_ref")
    @test haskey(res, "ambient_dose_equivalent_rate_ref")
    @test haskey(res, "energy_group_fluence_thermal_ref")
    @test haskey(res, "energy_group_fluence_fast_test")
    @test res["ambient_dose_equivalent_rate_ref"] > 0
    @test res["fluence_difference_percent"] ≈ 1.0 atol = 1e-10
    # zero total-fluence → 0
    zero_spec = zeros(length(E))
    res0 = compare_spectra(zeros(3), zeros(3); energy=E)
    @test res0["fluence_averaged_energy_ref"] == 0.0
    @test res0["ambient_dose_equivalent_rate_ref"] == 0.0
end

@testset "compare_multiple" begin
    a = Float64[1.0, 2.0, 3.0]
    b = Float64[2.0, 3.0, 4.0]
    c = Float64[1.0, 1.0, 1.0]
    out = compare_multiple([a, b, c];
                           labels=["Ref", "A", "B"])
    @test haskey(out, "Ref vs A") && haskey(out, "Ref vs B")
    @test out["Ref vs B"]["kl_divergence"] >= 0
end

@testset "BenchmarkUnfoldMethods" begin
    det = Detector()
    n = n_energy_bins(det)
    x_true = exp.(-energy_grid(det) ./ 2.0)
    refs = Dict{String,Vector{Float64}}("Deg_Sample" => x_true)
    bench = benchmark_unfold_methods(det, energy_grid(det), refs)
    @test bench isa BenchmarkResult
    @test length(bench.results) >= 3
    @test !isempty(bench.ranking)
    @test !isempty(bench.report)
    ok_rows = count(r -> r["success"], bench.results)
    @test ok_rows > 0
    # result row contains metrics
    ok_row = first(filter(r -> r["success"], bench.results))
    @test haskey(ok_row, "r2_score")
end
